export enum EggType {
  TOTAL = 'TOTAL',
  CRACKED = 'CRACKED',
  DIRTY_NEST = 'DIRTY_NEST',
  SMALL = 'SMALL',
  INCUBATABLE = 'INCUBATABLE',
  BROKEN = 'BROKEN',
  DEFORMED = 'DEFORMED',
  THIN_SHELL = 'THIN_SHELL',
  ELIMINATED = 'ELIMINATED',
  MARKET = 'MARKET'
}   